#!/bin/bash
# Jarvis Daily Backup Script
# Backs up all skills, config, and memories to GitHub
# Run via cron: 0 12 * * * /home/ubuntu/jarvis/scripts/daily-backup.sh
# Or: hermes cron create --schedule "0 12 * * *" --script ~/jarvis/scripts/daily-backup.sh

set -e

JARVIS_DIR="$HOME/jarvis"
HERMES_DIR="$HOME/.hermes"
BACKUP_DATE=$(date -u +"%Y-%m-%d_%H:%M:%S_UTC")

echo "🤖 Jarvis daily backup starting: $BACKUP_DATE"

# Ensure we're in the jarvis directory
cd "$JARVIS_DIR"

# Create hermes backup directories
mkdir -p "$JARVIS_DIR/hermes/skills"
mkdir -p "$JARVIS_DIR/hermes/memories"

# === BACKUP SKILLS ===
echo "🧠 Backing up skills..."
if [ -d "$HERMES_DIR/skills" ]; then
    # Clear old skills and copy fresh
    rm -rf "$JARVIS_DIR/hermes/skills/*"
    cp -r "$HERMES_DIR/skills/"* "$JARVIS_DIR/hermes/skills/" 2>/dev/null || true
    SKILL_COUNT=$(find "$JARVIS_DIR/hermes/skills" -name "SKILL.md" | wc -l)
    echo "   ✓ $SKILL_COUNT skills backed up"
else
    echo "   ⚠ No skills directory found"
fi

# === BACKUP CONFIG ===
echo "⚙️  Backing up config..."
if [ -f "$HERMES_DIR/config.yaml" ]; then
    cp "$HERMES_DIR/config.yaml" "$JARVIS_DIR/hermes/config.yaml"
    echo "   ✓ Config backed up"
else
    echo "   ⚠ No config.yaml found"
fi

# === BACKUP MEMORIES ===
echo "🧬 Backing up memories..."
if [ -d "$HERMES_DIR/memories" ]; then
    rm -rf "$JARVIS_DIR/hermes/memories/*"
    cp "$HERMES_DIR/memories/"* "$JARVIS_DIR/hermes/memories/" 2>/dev/null || true
    echo "   ✓ Memories backed up"
else
    echo "   ⚠ No memories directory found"
fi

# === UPDATE SKILLS.md INDEX ===
echo "📝 Regenerating SKILLS.md index..."
SKILL_COUNT=$(find "$JARVIS_DIR/hermes/skills" -name "SKILL.md" | wc -l)

# Update the "Last Updated" line in SKILLS.md
sed -i "s/\*\*Last Updated:\*\* .*/\*\*Last Updated:\*\* $BACKUP_DATE/" "$JARVIS_DIR/SKILLS.md" 2>/dev/null || true
sed -i "s/AUTO-GENERATED/$BACKBACKUP_DATE/" "$JARVIS_DIR/SKILLS.md" 2>/dev/null || true

# === GIT COMMIT & PUSH ===
echo "📤 Pushing to GitHub..."
git add -A

if git diff --cached --quiet; then
    echo "   ℹ No changes to commit"
    echo "✅ Backup complete (no changes)"
    exit 0
fi

git commit -m "auto-backup: $BACKUP_DATE

- Skills: $SKILL_COUNT active
- Config: synced
- Memories: synced
- Auto-generated by daily-backup.sh"

git push origin main

echo ""
echo "✅ Backup complete: $BACKUP_DATE"
echo "🔗 https://github.com/joking-really/jarvis"
